### ISSUE TITLE
Add bootstrap 4

### ISSUE THREAD

**Issue by dondogecl** [dondogecl/dogememos#1]
In order to improve the visuals, I think it would be a nice addition to install bootstrap for better visuals.

**Comment by aitorres** [comment]
Hello! I would like to take on this issue :-)

**Comment by aitorres** [comment]
I submitted a PR. If you can, check it out and let me know if you have any suggestions! @dondogecl

**Comment by dondogecl** [comment]
@aitorres well done!! will check it and if it is all good, then will merge.

**Comment by dondogecl** [comment]
Well done, Thank you. If you have any further improvement or suggestion, don't be afraid.
I will update the readme and open new issues with the new features needed.

**Comment by dondogecl** [comment]
It's working, any new design improvements will be listed as a new issue as needed.
