### ISSUE TITLE
add completed option

### ISSUE THREAD

**Issue by dondogecl** [dondogecl/dogememos#2]
it is necessary to add an option to show the completion of the task, it could be a switch or a checkbox that will change the status of the task.

- It will be necessary to modify the model to add the field to the model
- add the new code to generate that action
- modify the web/html to create that element in the table view

**Comment by dondogecl** [comment]
completed by @kalkehcoisa. TY

**Comment by kalkehcoisa** [comment]
Thanks! ;)
